#!/bin/bash

ECHOPREFIX="[GENECLIPSE]"

echo "${ECHOPREFIX} starting setup ..."

####################################################################
##	Setup Script
####################################################################
#
# Helper script to setup a proper Eclipse environment. Setups  
# Eclipse in the given folder, initializes the workspace with few 
# parameters, fix GTK2 startup, and install plugins. 
#
####################################################################

function check_java_version {
	JAVA8=0
	JAVA9=0
	JAVA8=`java -version 2>&1 | grep 1.8 | wc -l`
	if [ "$JAVA8" == "0" ]; then
		JAVA9=`java -version 2>&1 | grep 1.9 | wc -l`
		if [ "$JAVA9" == "0" ]; then
			cat << "EOF"

Eclipse requires Java 8 or higher. On debian like systems (as root) :
   $ apt-get install openjdk-8-jdk openjdk-8-source
   $ JVM=`update-java-alternatives -l | grep 1.8 | cut -d" " -f 1 | head -n 1` 
   $ update-java-alternatives -s $JVM
On other Linux distributions, Windows and MacOSX systems, please
visit http://www.oracle.com/technetwork/java/javase/downloads/index.html

EOF
			exit 1
		fi
	fi
}

function check_user {	
	USER=`whoami`
	[ "$USER" == "root" ] && echo "Should not be run as root" && exit 1
}

function check_homedir {	
	HOMEDIR=$HOME
	[ ! -d ${HOMEDIR} ] && HOMEDIR=`cat /etc/passwd | grep "$USER" | cut -d":" -f 6`
	[ ! -d ${HOMEDIR} ] && echo "Could not locate Home directory (${HOMEDIR})" && exit 1
}

function check_and_set_installation_path {
	installationpath="$1"
	[ "$1" == "" ] && read -p "Folder installation path: " installationpath

	if [ -d "${installationpath}" ]; then 
		if [ -d "${installationpath}/eclipse" ]; then 
			echo "Error: eclipse folder already exist at the location specified"
			exit 1
		fi
		if [ -d "${installationpath}/workspace" ]; then
			echo "Error: workspace folder already exist at the location specified"
			exit 1
		fi
	else
		mkdir -p ${installationpath}
	fi

	installationpath=`(cd ${installationpath} && echo $PWD)`
	#test write permission
	[ ! -w ${installationpath} ] && echo "Cannot write into ${installationpath}" && exit 1
}

function check_and_set_platform {
	# Supported platforms
	#   - Windows
	#   - Windows (x86_64)
	#   - Linux (x86/GTK+)
	#   - Linux (x86_64/GTK+)
	#   - Mac OSX (Mac/Cocoa/x86_64)

	PLATFORM=`uname -s`
	ARCH=`uname -m`

	ECLIPSE_ARCHSUFF=
	[ "${ARCH}" == "x86_64" ] && ECLIPSE_ARCHSUFF=-x86_64

	case $PLATFORM in
		Linux)
			ECLIPSE_PLATFORM=linux-gtk
			ARCHIVE_EXTENSION=tar.gz
			
			ECLIPSE_INIT_FOLDER="./eclipse/"
			ECLIPSE_BIN_FOLDER="./eclipse/"
			ECLIPSE_BIN_EXTENSTION=
			;;
		Darwin)
			ECLIPSE_PLATFORM=macosx-cocoa
			ARCHIVE_EXTENSION=tar.gz
			
			ECLIPSE_INIT_FOLDER="./Eclipse.app/Contents/Eclipse/"
			ECLIPSE_BIN_FOLDER="./Eclipse.app/Contents/MacOS/"
			ECLIPSE_BIN_EXTENSTION=
			;;
		CYGWIN_NT-6.1 | CYGWIN_NT-10.0)
			ECLIPSE_PLATFORM=win32
			ARCHIVE_EXTENSION=zip
			
			ECLIPSE_INIT_FOLDER="./eclipse/"
			ECLIPSE_BIN_FOLDER="./eclipse/"
			ECLIPSE_BIN_EXTENSTION=".exe"
			;;
		*)
			echo "Unsupported platform $PLATFORM."
			exit 1
			;;
	esac
	
	
	case ${ARCHIVE_EXTENSION} in
		tar.gz)
			which tar 2>&1 > /dev/null
			TARPRESENT=$?
			[ "$TARPRESENT" != 0 ] && echo "Could not locate tar" && exit 1
			;;
		zip)
			which unzip 2>&1 > /dev/null
			UNZIPPRESENT=$?
			[ "$UNZIPPRESENT" != 0 ] && echo "Could not locate unzip" && exit 1
			;;
		*)
			echo "error"
			exit 1
			;;
	esac
}

function check_and_set_download_tool {
	which wget 2>&1 > /dev/null
	WGETPRESENT=$?
	which curl 2>&1 > /dev/null
	CURLPRESENT=$?
	
	if [ "$CURLPRESENT" == "0" ]; then
		DOWNLOADTOOL=curl
		DOWNLOADOPTION="-o"
	else 
		if [ "$WGETPRESENT" == 0 ]; then
			DOWNLOADTOOL=wget
			DOWNLOADOPTION="-O"
		else
			echo "Could not locate download tools (WGet or CURL)."
			exit 1
		fi
	fi
}

function check_and_set_eclipse_mirror {
	# MIRROR List :
	#http://ftp.fau.de/eclipse/
	#http://mirror.ibcp.fr/pub/eclipse/
	#http://mirror.ibcp.fr/pub/eclipse/
	#http://ftp.halifax.rwth-aachen.de/eclipse/
	#http://eclipse.mirror.wearetriple.com/
	#http://artfiles.org/eclipse.org/
	#http://mirror.switch.ch/eclipse/
	
	MIRRORURL="http://ftp.fau.de/eclipse/"
	ECLIPSE_URL_PATH="technology/epp/downloads/release/${ECLIPSE_VERSION}/${ECLIPSE_VERSION_MINOR}/"
	ECLIPSE_ARCHIVE_NAME="eclipse-java-${ECLIPSE_VERSION}-${ECLIPSE_VERSION_MINOR}-${ECLIPSE_PLATFORM}${ECLIPSE_ARCHSUFF}.${ARCHIVE_EXTENSION}"
	URL="${MIRRORURL}${ECLIPSE_URL_PATH}${ECLIPSE_ARCHIVE_NAME}"
}

ECLIPSE_VERSION=neon
ECLIPSE_VERSION_MINOR=3

DARKTHEME=NO

#useful plugins
SETUP_SVN=YES 	# SVN Client
SETUP_EASYSHELL=YES		# External Terminal
SETUP_ANYEDITTOOLS=YES  # UI enhancement
SETUP_FINDBUGS=YES		# More error/warnings

SETUP_GRADLE=YES		# Web Tool Plugins
SETUP_ECLEMMAJCC=YES	# Java Code Coverage
SETUP_JAUTODOC=YES		# Java AutoDoc

SETUP_WTP=YES			# Web Tool Plugins
SETUP_JAVAFX=YES		# JavaFX Design Tools
SETUP_PHOTRAN=YES		# Fortran support (from PTP)
SETUP_DLTK=YES			# Dynamic Languages Toolkit

#specific plugins (deprecated)
SETUP_TEXCLIPSE=YES 	# latex support in eclipse

#causing annoying behavior
SETUP_EASE=NO			# Eclipse Advanced Scripting Environment

#failing ..
SETUP_PTP=NO			# Parallel Tools
SETUP_CUP_LEX=NO   		#cup & lex (similar to yacc & lex, but in java)
SETUP_TOMCAT=NO			# Tomcat plugin
SETUP_GRECLIPSE=NO 		#groovy for eclipse

#CAIRN plugins (deprecated)
SETUP_TOM=NO
SETUP_JNIMAP=NO
SETUP_GECOS_SCRIPT=NO
SETUP_GECOS_UI=NO

ECLIPSE_OPTIONS="-nosplash -consolelog"


{ ##	Check & config script
  ##################################
	
	check_user
	check_homedir
	check_java_version
	
	check_and_set_installation_path $1
	check_and_set_platform
	check_and_set_download_tool
	check_and_set_eclipse_mirror

	echo "${ECHOPREFIX} "
	echo "${ECHOPREFIX} Installing in ${installationpath}"
	echo "${ECHOPREFIX} Archive name : ${ECLIPSE_ARCHIVE_NAME}"
	echo "${ECHOPREFIX} URL = $URL"
	echo "${ECHOPREFIX} "
}

##################################
##	Setup Eclipse
##################################

{
	TMPFILE=$(mktemp tmp_XXXXXXX_${ECLIPSE_ARCHIVE_NAME})
	echo "${ECHOPREFIX} ${DOWNLOADTOOL} ${DOWNLOADOPTION} ${TMPFILE} ${URL}"
	${DOWNLOADTOOL} ${DOWNLOADOPTION} ${TMPFILE} ${URL}
	echo "${ECHOPREFIX} Extracting ..."
	case ${ARCHIVE_EXTENSION} in
		tar.gz)
			tar -xf ${TMPFILE} -C ${installationpath}
			;;
		zip)
			unzip -xq ${TMPFILE} -d ${installationpath}
			;;
		*)
			echo "Unsupported archive extension"
			exit 1
			;;
	esac
	rm ${TMPFILE}
	chmod -R +x ${installationpath}
	
	echo "${ECHOPREFIX} Setup done."
}

##################################
##	Config Eclipse
##################################

{
	TMPCONFFILE=$(mktemp tmp_XXXXXXX_eclipse.ini)
	mkdir -p ${HOMEDIR}/.eclipse
	#set master password
	echo "secretrandomsuperpoweredpasswordofthemegadeath" > ${HOMEDIR}/.eclipse/master
	echo -e "-eclipse.password\n${HOMEDIR}/.eclipse/master" > ${TMPCONFFILE}
	#Fix eclipse.ini : force GTK2
	if [ "$ECLIPSE_PLATFORM" == "linux-gtk" ]; then
		echo -e "--launcher.GTK_version\n2" >> ${TMPCONFFILE}
	fi
	cat ${installationpath}/${ECLIPSE_INIT_FOLDER}/eclipse.ini >> ${TMPCONFFILE}
	mv ${TMPCONFFILE} ${installationpath}/${ECLIPSE_INIT_FOLDER}/eclipse.ini

	#initialize configuration
	TMPCONFFILE=$(mktemp tmp_XXXXXXX_config.ini)
	cat ${installationpath}/${ECLIPSE_INIT_FOLDER}/configuration/config.ini | grep -v "osgi.instance.area.default" > $TMPCONFFILE
	mv $TMPCONFFILE ${installationpath}/${ECLIPSE_INIT_FOLDER}/configuration/config.ini
	cat >> ${installationpath}/${ECLIPSE_INIT_FOLDER}/configuration/config.ini << EOF
osgi.instance.area.default=${installationpath}/workspace
EOF
	#Config skip workspace selection
	mkdir -p ${installationpath}/${ECLIPSE_INIT_FOLDER}/configuration/.settings/
	cat > ${installationpath}/${ECLIPSE_INIT_FOLDER}/configuration/.settings/org.eclipse.ui.ide.prefs << "EOF"
SHOW_WORKSPACE_SELECTION_DIALOG=false
eclipse.preferences.version=1
EOF

	mkdir -p ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/
	#Always exit without prompt
	cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.ide.prefs << "EOF"
EXIT_PROMPT_ON_CLOSE_LAST_WINDOW=false
REFRESH_WORKSPACE_ON_STARTUP=true
eclipse.preferences.version=1
EOF

	echo "${ECHOPREFIX} Basic config done"
}

##################################
##	Setup Eclipse plug-ins
##################################

ECLIPSE="${installationpath}/${ECLIPSE_BIN_FOLDER}/eclipse${ECLIPSE_BIN_EXTENSTION} ${ECLIPSE_OPTIONS}"
P2APP="${ECLIPSE} -application org.eclipse.equinox.p2.director"

echo "${ECHOPREFIX} Testing eclipse p2 director application ..."
#{P2APP} -h > /dev/null
RES=0
if [ "$RES" != "0" ]; then
	echo "Something went wrong (could not execute p2 director application)."
	exit 1
fi

SETUP_RESULT_TMPFILE=`mktemp setup_result_tmpfile_XXXXXXXXXXXXXX.txt`
function setup_eclipse_plugins {
	TITLE=$1
	echo "${ECHOPREFIX}   * Installing '$TITLE' plugins"
	DESTFOLDER=$2
	REPO=$3
	shift
	shift
	shift
	FEATURES=
	while [ $# -ge 1 ]; do
		if [ "$FEATURES" != "" ]; then
			FEATURES+=" "
		fi
		FEATURE="-installIU $1"
		FEATURES+=`echo $FEATURE | sed 's/-installIU %U/-uninstallIU /g'`
		shift
	done
	echo "${ECHOPREFIX}      - P2 Repository  : $REPO"
	echo "${ECHOPREFIX}      - Eclipse folder : $DESTFOLDER"
	echo -n "${ECHOPREFIX}      - Features       : " #multiline echo
	echo "`echo $FEATURES | sed "s/ -/\n${ECHOPREFIX}                         -/g"`"
	echo "${ECHOPREFIX}    Launching ..."
	
	${P2APP} -repository ${REPO} -destination ${DESTFOLDER} ${FEATURES}
	SETUP_RESULT=$?
	echo "${ECHOPREFIX}   - $TITLE Setup : $SETUP_RESULT" >> $SETUP_RESULT_TMPFILE
	echo "${ECHOPREFIX}    $TITLE Setup done : $SETUP_RESULT"
	echo "${ECHOPREFIX}"
}

function finish {
	echo "${ECHOPREFIX}"
	echo "${ECHOPREFIX} Install results : "
	cat $SETUP_RESULT_TMPFILE
	echo "${ECHOPREFIX}"
	rm $SETUP_RESULT_TMPFILE
	exit
}

rm -f $SETUP_RESULT_TMPFILE
ECLIPSE_PLUGINS_INSTALL_PATH=${installationpath}/${ECLIPSE_INIT_FOLDER}

setup_eclipse_plugins \
	"Color Theme" \
	${ECLIPSE_PLUGINS_INSTALL_PATH} \
	http://eclipse-color-theme.github.io/update/ \
	com.github.eclipsecolortheme.feature.feature.group

finish

setup_eclipse_plugins \
	"cdt, xml, web, m2e, ..." \
	${ECLIPSE_PLUGINS_INSTALL_PATH} \
	http://download.eclipse.org/releases/${ECLIPSE_VERSION} \
	org.eclipse.cdt.feature.group \
	org.eclipse.cdt.platform.feature.group \
	org.eclipse.cdt.gnu.dsf.feature.group \
	org.eclipse.cdt.gnu.build.feature.group \
	org.eclipse.cdt.gnu.debug.feature.group \
	org.eclipse.cdt.gdb.feature.group \
	org.eclipse.cdt.debug.standalone.feature.group \
	org.eclipse.jst.web_ui.feature.feature.group \
	org.eclipse.jpt.jpa.feature.feature.group \
	org.eclipse.jpt.jpadiagrameditor.feature.feature.group \
	org.eclipse.wst.xsl.feature.feature.group \
	org.eclipse.wst.xml_ui.feature.feature.group \
	org.eclipse.wst.web_ui.feature.feature.group \
	org.eclipse.m2e.feature.feature.group \
	org.sonatype.m2e.mavenarchiver.feature.feature.group \
	org.eclipse.m2e.wtp.feature.feature.group \
	org.eclipse.jpt.jaxb.feature.feature.group \
	org.eclipse.tm.terminal.feature.feature.group \
	org.eclipse.stardust.modeling.wst-feature.feature.group \
	org.eclipse.linuxtools.changelog.feature.group \
	%Uorg.eclipse.egit.feature.group \
	org.eclipse.egit.feature.group \
	org.eclipse.egit.gitflow.feature.feature.group

finish

		echo ""
		echo " * Setup Xtet/Xtend/Mwe/Ecore"
		echo ""
		${ECLIPSE} \
		  -application org.eclipse.equinox.p2.director \
		  ${P2OPTIONS} \
		  -repository http://download.eclipse.org/releases/${ECLIPSE_VERSION} \
		  -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.emf.mwe2.runtime.sdk.feature.group \
		  -installIU org.eclipse.xtend.sdk.feature.group \
		  -installIU org.eclipse.xtext.sdk.feature.group
		TMF_RESULT=$?
	fi


	echo ""
	echo " * Setup Tycho"
	echo ""
	${ECLIPSE} ${OPTIONS} \
	  -application org.eclipse.equinox.p2.director \
	  -repository http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.8.0/N/0.8.0.201409231215/ \
	  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
	  -installIU org.sonatype.tycho.m2e.feature.feature.group
	TYCHO_RESULT=$?


	echo ""
	echo " * Setup Releng Tools"
	echo ""
	${ECLIPSE} ${OPTIONS} \
	  -application org.eclipse.equinox.p2.director \
	  -repository http://download.eclipse.org/eclipse/updates/4.6 \
	  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
	  -installIU org.eclipse.releng.tools.feature.group
	RELENG_RESULT=$?



	if [ "$SETUP_DLTK" == "YES" ]; then
		echo ""
		echo " * setup Dynamic Language ToolKit"
		echo ""
		
		
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/releases/${ECLIPSE_VERSION} \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.dltk.itcl.feature.group \
		  -installIU org.eclipse.dltk.ruby.feature.group \
		  -installIU org.eclipse.dltk.sh.feature.group
		DLTK_RESULT=$?
	fi


	if [ "$SETUP_GRADLE" == "YES" ]; then
		echo ""
		echo " * setup Gradle (buildship)"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/buildship/updates/e46/releases/1.0 \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.buildship.feature.group
		GRADLE_RESULT=$?
		
	fi

	if [ "$SETUP_SVN" == "YES" ]; then
		echo ""
		echo " * setup svn"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/releases/${ECLIPSE_VERSION} \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.team.svn.feature.group
		SVN_RESULT=$?
		
		echo ""
		echo " * Setup subversive"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://community.polarion.com/projects/subversive/download/eclipse/6.0/neon-site/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.polarion.eclipse.team.svn.connector.feature.group \
		  -installIU org.polarion.eclipse.team.svn.connector.svnkit18.feature.group
		SUBVERSIVE_RESULT=$?
	fi

	if [ "$SETUP_EASYSHELL" == "YES" ]; then
		echo ""
		echo " * Setup easyshell"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://anb0s.github.io/EasyShell \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU de.anbos.eclipse.easyshell.feature.feature.group
		EASYSHELL_RESULT=$?
	fi

	if [ "$SETUP_TEXCLIPSE" == "YES" ]; then
		echo ""
		echo " * Setup texclipse"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://texlipse.sourceforge.net \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU net.sourceforge.texlipse.feature.group
		TEXCLIPSE_RESULT=$?
	fi

	if [ "$SETUP_CUP_LEX" == "YES" ]; then
		echo ""
		echo " * Setup cup/lex"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://cup-lex-eclipse.sourceforge.net/update/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU pi.eclipse.cle.feature.group
		CUP_LEX_RESULT=$?
	fi

	if [ "$SETUP_TOM" == "YES" ]; then
		echo ""
		echo " * Setup TOM"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://gecos.gforge.inria.fr/updates/mars/snapshot/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU cairn.tools.tom.dev.feature.group
		TOM_RESULT=$?
	fi

	if [ "$SETUP_JNIMAP" == "YES" ]; then
		echo ""
		echo " * Setup jnimap"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://gecos.gforge.inria.fr/updates/mars/snapshot/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU cairn.tools.jni.mapper.feature.group
		JNIMAP_RESULT=$?
	fi

	if [ "$SETUP_GECOS_SCRIPT" == "YES" ]; then
		echo ""
		echo " * Setup gecos scripts"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://gecos.gforge.inria.fr/updates/mars/snapshot/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU gecos.framework.feature.group
		GECOS_SCRIPT_RESULT=$?
	fi

	if [ "$SETUP_GECOS_UI" == "YES" ]; then
		echo ""
		echo " * Setup gecos UI"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://gecos.gforge.inria.fr/updates/mars/snapshot/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU gecos.ui.feature.group \
		  -installIU gecos.alma.feature.group
		GECOS_UI_RESULT=$?
	fi

	if [ "$SETUP_GRECLIPSE" == "YES" ]; then
		echo ""
		echo " * Setup greclipse (groovy)"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.codehaus.groovy.eclipse.feature.feature.group \
		  -installIU org.codehaus.groovy.m2eclipse.feature.feature.group \
		  -installIU org.codehaus.groovy.jdt.patch.feature.group \
		  -installIU org.codehaus.groovy24.feature.feature.group
		GRECLIPSE_RESULT=$?
	fi

	if [ "$SETUP_ECLEMMAJCC" == "YES" ]; then
		echo ""
		echo " * Setup eclemmajcc (code coverage)"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://update.eclemma.org/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU com.mountainminds.eclemma.feature.feature.group
		ECLEMMAJCC_RESULT=$?
	fi

	if [ "$SETUP_JAUTODOC" == "YES" ]; then
		echo ""
		echo " * Setup JAutodoc"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://jautodoc.sourceforge.net/update/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU net.sf.jautodoc.feature.feature.group
		JAUTODOC_RESULT=$?
	fi

	if [ "$SETUP_ANYEDITTOOLS" == "YES" ]; then
		echo ""
		echo " * Setup anyedit tools"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://andrei.gmxhome.de/eclipse/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU AnyEditTools.feature.group
		ANYEDITTOOLS_RESULT=$?
	fi

	if [ "$SETUP_FINDBUGS" == "YES" ]; then
		echo ""
		echo " * Setup findbugs"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://findbugs.cs.umd.edu/eclipse/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU edu.umd.cs.findbugs.plugin.eclipse.feature.group
		FINDBUGS_RESULT=$?
	fi

	if [ "$SETUP_TOMCAT" == "YES" ]; then
		echo ""
		echo " * Setup Tocmat"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository https://sourceforge.net/projects/tomcatplugin/files/updatesite/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU net.sf.eclipse.tomcat.feature.feature.group
		TOMCAT_RESULT=$?
	fi

	if [ "$SETUP_PTP" == "YES" ]; then
		echo ""
		echo " * Setup Parallel Tools"
		echo ""
		
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/releases/${ECLIPSE_VERSION} \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.cdt.bupc.feature.group \
		  -installIU org.eclipse.cdt.core.parser.upc.feature.feature.group \
		  -installIU org.eclipse.cdt.core.parser.upc.sdk.feature.group \
		  -installIU org.eclipse.ptp.rdt.sync.cdt.feature.group \
		  -installIU org.eclipse.cdt.core.parser.upc.source.feature.group \
		  -installIU org.eclipse.tm.terminal.connector.remote.feature.feature.group
		PTP_PRE_RESULT=$?
		  
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/tools/ptp/updates/neon/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.ptp.feature.group \
		  -installIU org.eclipse.ptp.sdk.feature.group \
		  -installIU org.eclipse.ptp.rm.jaxb.contrib.feature.group \
		  -installIU org.eclipse.ptp.etfw.feedback.perfsuite.feature.group \
		  -installIU org.eclipse.ptp.etfw.tau.feature.group \
		  -installIU org.eclipse.ptp.etfw.tau.fortran.feature.group \
		  -installIU org.eclipse.ptp.fortran.feature.group \
		  -installIU org.eclipse.ptp.gem.feature.group \
		  -installIU org.eclipse.ptp.pldt.fortran.feature.group \
		  -installIU org.eclipse.ptp.pldt.upc.feature.group \
		  -installIU org.eclipse.ptp.sci.feature.group \
		  -installIU org.eclipse.ptp.debug.sdm.feature.group
		PTP_RESULT=$?
	fi

	if [ "$SETUP_PHOTRAN" == "YES" ]; then
		echo ""
		echo " * Setup Photran (from PTP)"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/tools/ptp/updates/neon/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.photran.feature.group \
		  -installIU org.eclipse.photran.xlf.feature.group \
		  -installIU org.eclipse.photran.intel.feature.group
		  #-installIU org.eclipse.ptp.rdt.sync.fortran.feature.group
		PHOTRAN_RESULT=$?
	fi

	if [ "$SETUP_WTP" == "YES" ]; then
		echo ""
		echo " * Setup WTP"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/webtools/repository/neon/ \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.jst.ws.cxf.feature.feature.group \
		  -installIU org.eclipse.jpt.common.eclipselink.feature.feature.group \
		  -installIU org.eclipse.jpt.dbws.eclipselink.feature.feature.group \
		  -installIU org.eclipse.jpt.jaxb.eclipselink.feature.feature.group \
		  -installIU org.eclipse.jpt.jpa.eclipselink.feature.feature.group \
		  -installIU org.eclipse.jst.ws.jaxws.dom.feature.feature.group \
		  -installIU org.eclipse.jst.ws.jaxws.feature.feature.group \
		  -installIU org.eclipse.jsf.feature.feature.group \
		  -installIU org.eclipse.jst.jsf.apache.trinidad.tagsupport.feature.feature.group \
		  -installIU org.eclipse.jst.webpageeditor.feature.feature.group \
		  -installIU org.eclipse.jst.server_adapters.feature.feature.group \
		  -installIU org.eclipse.jst.server_adapters.ext.feature.feature.group \
		  -installIU org.eclipse.jst.server_ui.feature.feature.group \
		  -installIU org.eclipse.wst.server_adapters.feature.feature.group
		WTP_RESULT=$?
	fi

	if [ "$SETUP_JAVAFX" == "YES" ]; then
		echo ""
		echo " * Setup JavaFX"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/efxclipse/updates-released/2.4.0/site \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.fx.ide.feature.feature.group
		JAVAFX_RESULT=$?
	fi

	if [ "$SETUP_EASE" == "YES" ]; then
		echo ""
		echo " * Setup EASE"
		echo ""
		${ECLIPSE} ${OPTIONS} \
		  -application org.eclipse.equinox.p2.director \
		  -repository http://download.eclipse.org/ease/update/release \
		  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
		  -installIU org.eclipse.ease.modules.charting.feature.feature.group \
		  -installIU org.eclipse.ease.modules.team.git.feature.feature.group \
		  -installIU org.eclipse.ease.lang.javascript.feature.feature.group \
		  -installIU org.eclipse.ease.lang.jvm.feature.feature.group \
		  -installIU org.eclipse.ease.python.jython.feature.feature.group \
		  -installIU org.eclipse.ease.modules.modeling.feature.feature.group \
		  -installIU org.eclipse.ease.modules.feature.feature.group \
		  -installIU org.eclipse.ease.lang.python.feature.feature.group \
		  -installIU org.eclipse.ease.lang.python.py4j.feature.feature.group \
		  -installIU org.eclipse.ease.modules.unittest.feature.feature.group \
		  -installIU org.eclipse.ease.lang.groovy.feature.feature.group \
		  -installIU org.eclipse.ease.lang.ruby.feature.feature.group
		EASE_RESULT=$?
	fi
}

echo ""
echo "####"
echo "#### CONFIGURATION "
echo "####"


##################################
##	Config Eclipse workspace
##################################
{
#Config Xtend compiler
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.xtend.core.Xtend.prefs << EOF
eclipse.preferences.version=1
outlet.DEFAULT_OUTPUT.cleanupDerived=false
outlet.DEFAULT_OUTPUT.derived=false
EOF

if [ "$DARKTHEME" == "YES" ]; then
	cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.e4.ui.css.swt.theme.prefs << EOF
themeid=org.eclipse.e4.ui.css.theme.high-contrast
EOF

	#config theme dark
	cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.e4.ui.css.swt.theme << EOF
	themeid=org.eclipse.e4.ui.css.theme.high-contrast
EOF

	#config tm terminal
	cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.tm.terminal.control.prefs << EOF
TerminalPrefInvertColors=true
EOF
fi

if [ "$SETUP_SVN" == "YES" ]; then
#Config SVN Console output
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.team.svn.ui.prefs << "EOF"
eclipse.preferences.version=1
preference.console.autoshow=1
preference.console.limitEnabled=false
EOF

#Force SVN Decorators in worksapce
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs << "EOF"
eclipse.preferences.version=1
ENABLED_DECORATORS=org.eclipse.team.svn.ui.decorator.SVNLightweightDecorator\:true,
EOF
fi

#Open SVG/HTML files with internet browser by default
INTERNET_BROWSER=none
if [ "`which iceweasel | wc -l`" == "1" ]; then
	INTERNET_BROWSER=iceweasel
else
	if [ "`which firefox | wc -l`" == "1" ]; then
		INTERNET_BROWSER=firefox
	fi
fi
if [ "${INTERNET_BROWSER}" != "none" ]; then
	cat >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs << EOF
editors=<?xml version\="1.0" encoding\="UTF-8"?>\n<editors>\n<descriptor file\="${INTERNET_BROWSER}" id\="${INTERNET_BROWSER}" internal\="false" label\="${INTERNET_BROWSER}" openMode\="4" open_in_place\="false" program_name\="${INTERNET_BROWSER}"/>\n</editors>
resourcetypes=<?xml version\="1.0" encoding\="UTF-8"?>\n<editors version\="3.1">\n<info extension\="svg" name\="*">\n<editor id\="${INTERNET_BROWSER}"/>\n<defaultEditor id\="${INTERNET_BROWSER}"/>\n</info>\n<info extension\="htm" name\="*">\n<editor id\="${INTERNET_BROWSER}"/>\n<defaultEditor id\="${INTERNET_BROWSER}"/>\n</info>\n<info extension\="html" name\="*">\n<editor id\="${INTERNET_BROWSER}"/>\n<defaultEditor id\="${INTERNET_BROWSER}"/>\n</info>\n</editors>
EOF
fi

#skip wizard tab on startup
mkdir -p ${installationpath}/workspace/.metadata/.plugins/org.eclipse.ui.intro/
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.ui.intro/introstate << "EOF"
<?xml version="1.0" encoding="UTF-8"?>
<state reopen="false"/>
EOF

#Config skip workspace selection
mkdir -p ${installationpath}/eclipse/configuration/.settings/
cat > ${installationpath}/eclipse/configuration/.settings/org.eclipse.ui.ide.prefs << "EOF"
SHOW_WORKSPACE_SELECTION_DIALOG=false
eclipse.preferences.version=1
EOF

#Always exit without prompt
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.ide.prefs << "EOF"
EXIT_PROMPT_ON_CLOSE_LAST_WINDOW=false
REFRESH_WORKSPACE_ON_STARTUP=true
eclipse.preferences.version=1
EOF


if [ "$SETUP_EASYSHELL" == "YES" ]; then
#Config Easyshell terminal & explorer
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs << EOF
IdStr=cmdUnknown
eclipse.preferences.version=1
listPreference=-1
targetRunPreference=cd {1} && run ./''{3}''
EOF
TERMS="terminator xfce4-terminal gnome-terminal konsole urxvtc"
for term in ${TERMS}; do
	if [ ! -z `which ${term}` -a -x `which ${term}` ];
	then
		case ${term} in
			terminator)
				echo "targetPreference=terminator --working-directory\\={1}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			xfce4-terminal)
				echo "targetPreference=xfce4-terminal --default-working-directory\\={1}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			gnome-terminal)
				echo "targetPreference=gnome-terminal --working-directory\\={1}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			konsole)
				echo "targetPreference=konsole --workdir {1}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			urxvtc)
				echo "targetPreference=urxvtc -cd  {1}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			*)
				echo "unknown terminal ${term}"
				;;
		esac
		break
	fi
done
NAVS="thunar nautilus konqueror firefox"
for nav in ${NAVS}; do
	if [ ! -z `which ${nav}` -a -x `which ${nav}` ];
	then
		case ${nav} in
			thunar)
				echo "targetExplorePreference=thunar {2}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			nautilus)
				echo "targetExplorePreference=nautilus {2}" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			konqueror)
				echo "targetExplorePreference=konqueror file:\"{2}\"" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			firefox)
				echo "targetExplorePreference=firefox file:\"{2}\"" >> ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.tetrade.eclipse.plugins.easyshell.prefs
				;;
			*)
				echo "unknown file explorer ${nav}"
				;;
		esac
		break
	fi
done
fi


# DEPRECATED
#config Tom/Gom
cat > ${installationpath}/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/fr.loria.eclipse.tom.prefs << EOF 
eclipse.preferences.version=1
included_file_location=${installationpath}/workspace/eu.alma.matlab/src-gen/tom\:${installationpath}/workspace/eu.alma.matlab.frontend/src-tom\:${installationpath}/workspace/fr.irisa.cairn.gecos.model/src-gen/tom\:${installationpath}/workspace/fr.irisa.cairn.gecos.model.scop/src-gen/tom\:${installationpath}/workspace/org.polymodel.algebra/src-gen/tom\:${installationpath}/workspace/org.polymodel.polyhedralIR/src-gen/tom\:${installationpath}/workspace/org.polymodel.scop/src-gen/tom\:${installationpath}/workspace/org.polymodel.scop.dtiler/src-tom\:
EOF
}

CLEANUP_SCRIPT=${installationpath}/cleanup.sh
cat > ${CLEANUP_SCRIPT} << 'EOF'
#!/bin/bash

SCRIPT_DIR=`dirname $0` 
SCRIPT_DIR=`(cd ${SCRIPT_DIR} && echo $PWD)`
SCRIPT_NAME=`basename $0`

ECLIPSE_PATH=${SCRIPT_DIR}/eclipse
ECLIPSE_BIN=${ECLIPSE_PATH}/eclipse

WORKSPACE_PATH=${SCRIPT_DIR}/workspace/

PID=`ps -df | grep -v grep | grep /home/koubi/IDE/eclipse/eclipse | xargs | cut -d" " -f 2`

if [ "$PID" != "" ]; then 
	echo ""
	echo " ** Eclipse is found running (pid = $PID). Killing it."
	echo ""
	kill -9 $PID
fi


rm -f ${WORKSPACE_PATH}/.metadata/.lock
rm -f ${WORKSPACE_PATH}/.metadata/.log
rm -f ${WORKSPACE_PATH}/.metadata/.plugins/org.eclipse.core.resources/.span

if [ -d ${WORKSPACE_PATH}/.metadata/.plugins/org.eclipse.core.resources ]; then
	mv ${WORKSPACE_PATH}/.metadata/.plugins/org.eclipse.core.resources ${SCRIPT_DIR}/resources_bk
	
	echo ""
	echo " ** Eclipse will start. Close all tabs then close eclipse"
	echo ""
	read -p "[Press Enter] ..."

	${ECLIPSE_BIN}

	rm -rf ${WORKSPACE_PATH}/.metadata/.plugins/org.eclipse.core.resources
	mv ${SCRIPT_DIR}/resources_bk ${WORKSPACE_PATH}/.metadata/.plugins/org.eclipse.core.resources
fi

echo ""
echo " ** Cleanup done."
echo ""

exit 0

EOF
chmod +x ${CLEANUP_SCRIPT}

echo "####"
echo "#### done "
echo "####"

[ ! -z $JAVAFX_RESULT ] && echo "JavaFX : $JAVAFX_RESULT"
[ ! -z $WTP_RESULT ] && echo "Web Tools : $WTP_RESULT"
[ ! -z $PHOTRAN_RESULT ] && echo "Fortran : $PHOTRAN_RESULT"
[ ! -z $PTP_RESULT ] && echo "Parallel Tools : $PTP_RESULT"
[ ! -z $PTP_PRE_RESULT ] && echo "Parallel Tools (prereq) : $PTP_PRE_RESULT"
[ ! -z $TOMCAT_RESULT ] && echo "Tomcat : $TOMCAT_RESULT"
[ ! -z $FINDBUGS_RESULT ] && echo "Findbugs : $FINDBUGS_RESULT"
[ ! -z $ANYEDITTOOLS_RESULT ] && echo "Any Edit Tools : $ANYEDITTOOLS_RESULT"
[ ! -z $JAUTODOC_RESULT ] && echo "JAutoDoc : $JAUTODOC_RESULT"
[ ! -z $ECLEMMAJCC_RESULT ] && echo "Code Coverage : $ECLEMMAJCC_RESULT"
[ ! -z $GRECLIPSE_RESULT ] && echo "GreClipse : $GRECLIPSE_RESULT"
[ ! -z $GECOS_UI_RESULT ] && echo "Gecos UI : $GECOS_UI_RESULT"
[ ! -z $GECOS_SCRIPT_RESULT ] && echo "Gecos Script : $GECOS_SCRIPT_RESULT"
[ ! -z $JNIMAP_RESULT ] && echo "JNIMap : $JNIMAP_RESULT"
[ ! -z $CUP_LEX_RESULT ] && echo "Cup/Lex : $CUP_LEX_RESULT"
[ ! -z $TEXCLIPSE_RESULT ] && echo "TexClipse : $TEXCLIPSE_RESULT"
[ ! -z $EASYSHELL_RESULT ] && echo "EasyShell : $EASYSHELL_RESULT"
[ ! -z $SUBVERSIVE_RESULT ] && echo "SubVersive : $SUBVERSIVE_RESULT"
[ ! -z $SVN_RESULT ] && echo "SVN : $SVN_RESULT"
[ ! -z $GRADLE_RESULT ] && echo "Gradle : $GRADLE_RESULT"
[ ! -z $TMF_RESULT ] && echo "TMF : $TMF_RESULT"
[ ! -z $BASE_RESULT ] && echo "Base Setup : $BASE_RESULT"
[ ! -z $COLORTHEME_RESULT ] && echo "Color Themes : $COLORTHEME_RESULT"
[ ! -z $EASE_RESULT ] && echo "EASE : $EASE_RESULT"
[ ! -z $DLTK_RESULT ] && echo "DLTK : $DLTK_RESULT"
[ ! -z $TYCHO_RESULT ] && echo "Tycho : $TYCHO_RESULT"
[ ! -z $RELENG_RESULT ] && echo "Releng Tools : $RELENG_RESULT"



exit
##################################
##	END.
##################################

#archive:
	  
	echo ""
	echo " * Setup TMF"
	echo ""
	${ECLIPSE} ${OPTIONS} \
	  -application org.eclipse.equinox.p2.director \
	  -repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/ \
	  ${P2OPTIONS} -destination ${installationpath}/eclipse/ \
	  -installIU org.eclipse.xtext.sdk.feature.group \
	  -installIU org.eclipse.xtext.xbase.source.feature.group \
	  -installIU org.eclipse.xtext.xbase.feature.group \
	  -installIU org.eclipse.xtext.xbase.lib.source.feature.group \
	  -installIU org.eclipse.xtext.xbase.lib.feature.group \
	  -installIU org.eclipse.xtext.examples.source.feature.group \
	  -installIU org.eclipse.xtext.examples.feature.group \
	  -installIU org.eclipse.xtext.ui.source.feature.group \
	  -installIU org.eclipse.xtext.ui.feature.group \
	  -installIU org.eclipse.xtext.xtext.ui.source.feature.group \
	  -installIU org.eclipse.xtext.xtext.ui.feature.group \
	  -installIU org.eclipse.xtext.docs.feature.group \
	  -installIU org.eclipse.xtext.runtime.source.feature.group \
	  -installIU org.eclipse.xtext.runtime.feature.group \
	  -installIU org.eclipse.xtend.sdk.feature.group \
	  -installIU org.eclipse.emf.mwe2.runtime.sdk.feature.group \
	  -installIU org.eclipse.emf.mwe2.runtime.sdk.source.feature.group \
	  -installIU org.eclipse.emf.ecore.xcore.feature.group
