#!/bin/bash -eu

USER=`whoami`
[ "$USER" == "root" ] && echo "Should not be run as root" && exit 1

[ $# -lt 1 ] && ARG1="" || ARG1=$1

SOURCE_SCRIPT=http://koub.org/files/linux/02_apps/gen-eclipse/gen-eclipse

TMPFILE=`mktemp`
wget $SOURCE_SCRIPT -O $TMPFILE
chmod +x $TMPFILE
$TMPFILE $ARG1
rm $TMPFILE
